### PR TITLE
Results after backward search

### PR DESCRIPTION
**Pull request by mpoqq**

### CODE REVIEW

**Comment by xJREB** [comment]
Remember also to update the CSV files in the `slr` folder, if snowballing resulted in additional primary studies. Or maybe add `slr_articles_phase_4.csv` with the results after snowballing.

**Comment by boceckts** [comment]
👍 for the second option

**Comment by mpoqq** [comment]
@boceckts can you please update the pictures (slr.pdf, ...)

**Comment by boceckts** [comment]
> 
> 
> @boceckts can you please update the pictures (slr.pdf, ...)

I think you also modified the number of articles in #117  and #119 . Can you update this branch to the master, then I will recreate the files based on this branch and push it to this PR.

**Pull request merged**
