### PR TITLE
[WIP] Antipattern documentation refinement

### PR DESCRIPTION
**Pull request by xJREB**
Major revision of the JSON files; please have a look at your antipatterns and review if this is still in line with the literature. Moreover, I stumbled across the following antipattern pairs that may be candidates for merging:

- `Golden Hammer` and `Silver Bullet`
- `CRUDy Interface` and `Maybe It is Not RPC`
- `Extraneous Adjacent Connector` and `Redundant PortTypes`

Are these antipatterns significantly different so that it would be beneficial to keep them separate? What do you think?

### CODE REVIEW

**Comment by xJREB** [comment]
OK, since this will have effects on the publication and text, tables, and figures will have to be updated, I suggest that we do this right away. I try to provide a commit for this ASAP that your can then review.

**Comment by xJREB** [comment]
OK, after also reviewing Shine Nickel, I propose to keep all three separate (`The Shiny Nickel`, `Golden Hammer`, and `Silver Bullet`). They are all similar and related, but have a slightly different notions. So I guess it is worth it.

`CRUDy Interface` and `Maybe It is Not RPC` as well as `Extraneous Adjacent Connector` and `Redundant PortTypes` were merged by me (I kept the first name as the primary one).

Please review this before you merge it.

**Comment by xJREB** [comment]
> Because `CRUDy Interface` and `Maybe It is Not RPC` has the same two sources and they also defined these as separated antipatterns I think they are not the same.

I also saw that the they are from the same source, but I still fail to see a significant difference. Both stress that an RPC-like behaviour with CRUD operations is bad, because it leads to chatty APIs and therefore poor system performance. What would be the different notions I miss?

**Comment by mpoqq** [comment]
@tschechlovdev and I have discussed it again and we agree with you. Keeping them separate is perhaps more confusing than merging them together.

**Comment by xJREB** [comment]
OK, then I merge this and kindly ask you to update the numbers for antipatterns and categories everywhere. 👼

**Pull request merged**
