### PR TITLE
Add evidence

### PR DESCRIPTION
**Pull request by mpoqq**
Add evidence and change colour on the side of the card title based on the median evidence.
image
image

### CODE REVIEW

**Comment by mpoqq** [comment]
Maybe also add the evidence in the detail component

**Comment by boceckts** [comment]
Refs #12

**Comment by mpoqq** [comment]
> or the same color with different shades

This is the actual approach, the evidence is mapped to the alpha channel. Red is currently the base colour. We can also change it to something else. 

The clarify the colours we can set the evidence at filter options. The user then knows which colour it stands for and in addition we have another filter. =)

**Comment by mpoqq** [comment]
Now with Filter:
image

**Comment by mpoqq** [comment]
Color is now Cyan  `#00acc1`

**Pull request merged**
